// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7U4VPyW_35UPxD6s76VQ68FQoceK9u2M',
    appId: '1:958919089386:web:707b6a1f7b304c55730b93',
    messagingSenderId: '958919089386',
    projectId: 'booksread-3cbfd',
    authDomain: 'booksread-3cbfd.firebaseapp.com',
    storageBucket: 'booksread-3cbfd.appspot.com',
    measurementId: 'G-4DV4CGRQ8X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpX7E3xs_LICN6qYdzGT5JnfAXWli_lA0',
    appId: '1:958919089386:android:d67a7a83afb70f46730b93',
    messagingSenderId: '958919089386',
    projectId: 'booksread-3cbfd',
    storageBucket: 'booksread-3cbfd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACCkkbg4IT9pM7COi1a-I-QH7Ud03RIQM',
    appId: '1:958919089386:ios:8c04038c55ef6ec2730b93',
    messagingSenderId: '958919089386',
    projectId: 'booksread-3cbfd',
    storageBucket: 'booksread-3cbfd.appspot.com',
    iosBundleId: 'com.example.books',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACCkkbg4IT9pM7COi1a-I-QH7Ud03RIQM',
    appId: '1:958919089386:ios:8c04038c55ef6ec2730b93',
    messagingSenderId: '958919089386',
    projectId: 'booksread-3cbfd',
    storageBucket: 'booksread-3cbfd.appspot.com',
    iosBundleId: 'com.example.books',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7U4VPyW_35UPxD6s76VQ68FQoceK9u2M',
    appId: '1:958919089386:web:e7da0379bb8ba3d0730b93',
    messagingSenderId: '958919089386',
    projectId: 'booksread-3cbfd',
    authDomain: 'booksread-3cbfd.firebaseapp.com',
    storageBucket: 'booksread-3cbfd.appspot.com',
    measurementId: 'G-RVKDEC5DFP',
  );
}
